### ISSUE TITLE
wavelink.Player.connect incompatibility with Discord.py 2.0

### ISSUE THREAD

**Issue by Luc1412** [PythonistaGuild/Wavelink#153]
Discord.py 2.0 introduced a new `self_deaf` and `self_mute` parameter to the connect method. This causes `TypeError: Player.connect() got an unexpected keyword argument 'self_deaf'`

**Comment by chillymosh** [comment]
I think the choice of words of the issue could be better. It's not that Wavelink is incompatible with dpy 2.0, as the lib works fine with 2.0, in fact 1.x was built for 2.0. 
It's that you're using new features of one that is not yet in another and expecting it to work.

These will most likely be added in due course.

**Comment by Luc1412** [comment]
Well atm wavelink isn't compatible with d.py 2.0 as connecting raises an error due to the missing params. 

The better wording might be "latest commits if d.py 2.0"

**Comment by chillymosh** [comment]
A workaround is to change the Player.connect() method to this for now, until it's officially added

```
    async def connect(self, *, timeout: float, reconnect: bool, self_deaf: bool, self_mute: bool) -> None:
        self_deaf = True
        await self.guild.change_voice_state(channel=self.channel, self_deaf=self_deaf, self_mute=self_mute)
        self._connected = True

        logger.info(f"Connected to voice channel:: {self.channel.id}")
```

**Comment by Luc1412** [comment]
Fixed with #155
